spark.jars.packages     org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.3,org.mongodb.spark:mongo-spark-connector_2.12:10.4.0

spark.mongodb.read.connection.uri    mongodb://mongodb:27017/
spark.mongodb.write.connection.uri   mongodb://mongodb:27017/
